config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :recruiters, controllers: {
    sessions:      'recruiters/sessions',
    passwords:     'recruiters/passwords',
    registrations: 'recruiters/registrations'
  }

  devise_for :employees, controllers: {
    sessions:      'employees/sessions',
    passwords:     'employees/passwords',
    registrations: 'employees/registrations'
  }

  resources :recruiters, path: '/recruiters', param: :username, only: [] do
    scope module: 'recruiters' do
      resources :jobs, only: [:index, :create, :new, :edit, :update, :destroy] do
        # resources :applicants, only: [:index, :show, :update]  # 追加
        collection do
          post :confirm
          get :fetch_recruiters, defaults: { format: 'json' }
        end
        member do
          patch :edit_confirm
        end
      end
    end
  end


  resources :jobs, module: 'employees', only: [:index, :show] do
    resources :job_applications, only: [:new, :create] do
      collection do
        post :confirm
      end
    end
  end

  resources :jobs do
    resources :applicants, only: [:index, :show, :edit, :update]
  end

  resources :employees, param: :username, only: [] do
    resources :job_applications, module: 'employees', only: [:index, :show]
    resource :profile, module: 'employees', only: [:show, :edit, :update] do
      collection do
        post :edit_confirm
      end
    end
  end

  # resources :admins, only: [] do
  resources :admins, path: '/admins', param: :username, only: [] do
    scope module: 'admins' do
      resources :jobs, only: [:index, :show] do
      end
    end
  end

  root 'employees/jobs#index'


end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :employee_profile, dependent: :destroy
  has_many :job_applications

  def to_param
    username
  end
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/job_applications_controller.rb
class Employees::JobApplicationsController < ApplicationController
  protect_from_forgery except: :index
  before_action :authenticate_employee!
  before_action :set_job, only: [:new, :confirm, :create]
  before_action :set_root_departments, only: [:index, :new, :confirm, :create, :show]

  def index
    job_ids = current_employee.employee_profile.job_applications.order(created_at: :desc).pluck(:job_id)

    @q = Job.where(id: job_ids).ransack(params[:q])
    # @jobs = @q.result.order(Arel.sql("FIELD(id, #{job_ids.join(',')})")).includes(:job_applications).page(params[:page]).per(10)
    order_clause = job_ids.map.with_index{ |id, index| "WHEN #{id} THEN #{index}" }.join(" ")
    @jobs = @q.result
          .order(Arel.sql("CASE jobs.id #{order_clause} END"))
          .includes(:job_applications)
          .page(params[:page])
          .per(10)

    @application_statuses = {}
    @application_dates = {}

    @jobs.each do |job|
      job_application = JobApplication.find_by(job: job, applicant: current_employee.employee_profile)
      @application_statuses[job.id] = job_application.current_status.name if job_application

      application_date = job_application&.created_at
      @application_dates[job.id] = application_date
    end
  end

  def new
    if JobApplication.exists?(job: @job, applicant: current_employee.employee_profile)
      redirect_to job_path(params[:job_id]), alert: '既に応募済みです。'
      return
    end

    if @job.department == current_employee.employee_profile.department
      redirect_to job_path(params[:job_id]), alert: '自分の所属する部門の求人には応募できません。'
      return
    end

    @job_application = if session[:job_application_data]
                      data = session[:job_application_data]
                      session.delete(:job_application_data)
                      JobApplication.new(data)
                    else
                      JobApplication.new
                    end
  end


  def confirm
    @job_application = JobApplication.new(job_application_params.merge({
      job_id: @job.id,
      applicant_id: current_employee.employee_profile.id
    }))
    session[:job_application_data] = job_application_params

    unless @job_application.valid?
      Rails.logger.debug(@job_application.errors.full_messages)
      render :new
    end
  end

  def create
    @job_application = @job.job_applications.new(session[:job_application_data])
    @job_application.applicant = current_employee.employee_profile  # 仮にcurrent_employeeメソッドが現在のEmployeeを返すとします。

    if @job_application.save
      session.delete(:job_application_data)  # セッションのクリア
      redirect_to employee_job_applications_path(current_employee), notice: '応募が完了しました'
    else
      puts @job_application.errors.full_messages
      puts "Session data: #{session[:job_application_data]}"
      render :new
    end
  end

  def show
    @job_application = JobApplication.find(params[:id])
    @job = @job_application.job
  end


  private

  def set_job
    @job = Job.find(params[:job_id])
  end

  def job_application_params
    # 必要なパラメータを許可します
    params.require(:job_application).permit(:reason_for_application, :self_promotion)
  end

  def set_root_departments
    @root_departments = Department.where(ancestry: nil)
  end
end

app/controllers/employees/jobs_controller.rb
class Employees::JobsController < ApplicationController
  protect_from_forgery except: :index
  before_action :set_root_departments, only: [:index, :show]
  before_action :set_categories, only: [:index]

  def index
    public_status_id = JobStatus.find_by(name: '公開中').id

    category_filter = if params[:category].present?
      category = Category.find(params[:category].to_i)
    else
      Category.all.pluck(:id)
    end

    if params[:department].present? && params[:department] =~ /\A\d+\z/
      department_filter = Department.find(params[:department].to_i).subtree.pluck(:id)
      @department_name = Department.find_by(id: params[:department]).path.map(&:name).join
    else
      department_filter = Department.all.pluck(:id)
      @department_name = "すべて部門の求人"
    end

    sub_query = JobStatusMap.select('job_id, MAX(created_at) as max_created_at').group(:job_id)

    @q = Job.ransack(params[:q])
    @jobs = @q.result
          .includes(:category, job_status_maps: :job_status)
          .joins(:job_status_maps)
          .joins("INNER JOIN (#{sub_query.to_sql}) AS latest_statuses ON job_status_maps.job_id = latest_statuses.job_id AND job_status_maps.created_at = latest_statuses.max_created_at")
          .where(department_id: department_filter, category_id: category_filter, job_status_maps: { job_status_id: public_status_id })
          .order('job_status_maps.created_at DESC')
          .page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js # これを追加
    end
  end

  def show
    session.delete(:job_application_data) if session[:job_application_data]
    @job = Job.find(params[:id])

    # if current_employee
    #   @already_applied = JobApplication.exists?(job: @job, applicant: current_employee.employee_profile)
    # else
    #   @already_applied = false
    # end
    if current_employee
      @already_applied = JobApplication.exists?(job: @job, applicant: current_employee.employee_profile)
      @same_department = @job.department == current_employee.employee_profile.department
    else
      @already_applied = false
      @same_department = false
    end
  end

  private

  def set_root_departments
    @root_departments = Department.where(ancestry: nil)
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/profiles_controller.rb
class Employees::ProfilesController < ApplicationController
  before_action :authenticate_employee!
  before_action :set_root_departments, only: [:show, :edit, :update, :edit_confirm]
  before_action :set_employee_profile, only: [:show, :edit, :update, :edit_confirm]

  def show
  end

  def edit
    # セッションに変更内容が存在する場合、それを@employee_profileに適用する
    if session[:temp_profile_params]
      @employee_profile.assign_attributes(session[:temp_profile_params])
      session.delete(:temp_profile_params)  # セッションの変更内容をクリアする
    end
  end

  def edit_confirm
    @employee_profile.assign_attributes(profile_params)
    unless @employee_profile.valid?
      render :edit
    else
      # バリデーションが成功した場合、変更内容をセッションに保存する
      session[:temp_profile_params] = profile_params
    end
  end

  def update
    # 更新処理が成功したら、セッションの変更内容をクリアする
    if @employee_profile.update(profile_params)
      session.delete(:temp_profile_params)
      redirect_to employee_profile_path, notice: 'プロファイルを更新しました。'
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:employee_profile).permit(:qualifications, :skills)
  end

  def set_root_departments
    @root_departments = Department.where(ancestry: nil)
  end

  def set_employee_profile
    @employee_profile = current_employee.employee_profile
  end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    edit_employee_registration_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/employees/accounts_helper.rb
module Employees::AccountsHelper
end

app/helpers/employees/job_applications_helper.rb
module Employees::JobApplicationsHelper
   
end

app/helpers/employees/jobs_helper.rb
module Employees::JobsHelper
end

app/views/employees/shared/_aside.html.erb
<aside class="relative bg-sidebar w-1/6 hidden sm:block shadow-xl overflow-y-auto h-screen position-fixed flex flex-col items-center">
  <div class="p-6 w-full flex justify-center">
    <%= link_to jobs_path, class: "flex title-font font-medium items-center text-gray-900" do %>
      <%= image_tag 'logo.png', class: 'w-28 h-28 rounded-full' %>
    <% end %>
  </div>
  <nav class="text-white text-base font-semibold w-full flex flex-col items-center">
    <div class="">
      <%= link_to "#すべての求人", jobs_path, data: { department_id: '' }, class: 'block px-4 py-2 mt-2 department-link' %>
      <% @root_departments.each do |department| %>
        <%= link_to department.name, jobs_path(department: department.id), data: { department_id: department.id }, class: 'block px-4 py-2 mt-2 department-link' %>
      <% end %>
    </div>
  </nav>
</aside>

app/views/employees/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/employees/shared/_header.html.erb
<!-- Desktop Header -->
<header class="w-full items-center bg-white py-3 px-6 hidden sm:flex header-fixed">
  <div class="w-1/2"></div>
  <div x-data="{ isOpen: false }" class="relative w-1/2 flex justify-end">
      <% if current_employee.present? %>
          <button @click="isOpen = !isOpen" class="relative z-10 focus:outline-none">
              <%= current_employee.username %>
          </button>
          <button x-show="isOpen" @click="isOpen = false" class="h-full w-full fixed inset-0 cursor-default"></button>
          <div x-show="isOpen" x-cloak class="absolute w-32 bg-white rounded-lg shadow-lg py-2 mt-16">
            <%= link_to 'プロファイル情報', employee_profile_path(current_employee.username), class: "block px-4 py-2 account-link hover:text-white" %>
            <%= link_to '応募求人一覧', employee_job_applications_path(current_employee.username), class: "block px-4 py-2 account-link hover:text-white" %>
            <%= link_to "ログアウト", destroy_employee_session_path, method: :get, class: "block px-4 py-2 account-link hover:text-white" %>
          </div>
      <% else %>
          <span class="mr-4">ゲストユーザー</span>
          <%= link_to "ログイン", new_employee_session_path, class: "btn btn-primary" %>
      <% end %>
  </div>
</header>

<!-- Mobile Header & Nav -->
<header x-data="{ isOpen: false }" class="w-full bg-sidebar py-5 px-6 sm:hidden">
  <div class="flex items-center justify-between">
      <a href="index.html" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">Admin</a>
      <button @click="isOpen = !isOpen" class="text-white text-3xl focus:outline-none">
          <i x-show="!isOpen" class="fas fa-bars"></i>
          <i x-show="isOpen" class="fas fa-times"></i>
      </button>
  </div>

  <!-- Dropdown Nav -->
  <nav :class="isOpen ? 'flex': 'hidden'" class="flex flex-col pt-4">
      <a href="index.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-tachometer-alt mr-3"></i>
          Dashboard
      </a>
      <a href="blank.html" class="flex items-center active-nav-link text-white py-2 pl-4 nav-item">
          <i class="fas fa-sticky-note mr-3"></i>
          Blank Page
      </a>
      <a href="tables.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-table mr-3"></i>
          Tables
      </a>
      <a href="forms.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-align-left mr-3"></i>
          Forms
      </a>
      <a href="tabs.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-tablet-alt mr-3"></i>
          Tabbed Content
      </a>
      <a href="calendar.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-calendar mr-3"></i>
          Calendar
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-cogs mr-3"></i>
          Support
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-user mr-3"></i>
          My Account
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-sign-out-alt mr-3"></i>
          Sign Out
      </a>
      <button class="w-full bg-white cta-btn font-semibold py-2 mt-3 rounded-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
          <i class="fas fa-arrow-circle-up mr-3"></i> Upgrade to Pro!
      </button>
  </nav>
  <!-- <button class="w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
      <i class="fas fa-plus mr-3"></i> New Report
  </button> -->
</header>

app/views/employees/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>