config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :recruiters, controllers: {
    sessions:      'recruiters/sessions',
    passwords:     'recruiters/passwords',
    registrations: 'recruiters/registrations'
  }

  devise_for :employees, controllers: {
    sessions:      'employees/sessions',
    passwords:     'employees/passwords',
    registrations: 'employees/registrations'
  }

  resources :recruiters, path: '/recruiters', param: :username, only: [] do
    scope module: 'recruiters' do
      resources :jobs, only: [:index, :create, :new, :edit, :update, :destroy] do
        # resources :applicants, only: [:index, :show, :update]  # 追加
        collection do
          post :confirm
          get :fetch_recruiters, defaults: { format: 'json' }
        end
        member do
          patch :edit_confirm
        end
      end
    end
  end


  resources :jobs, module: 'employees', only: [:index, :show] do
    resources :job_applications, only: [:new, :create] do
      collection do
        post :confirm
      end
    end
  end

  resources :jobs do
    resources :applicants, only: [:index, :show, :edit, :update]
  end

  resources :employees, param: :username, only: [] do
    resources :job_applications, module: 'employees', only: [:index, :show]
    resource :profile, module: 'employees', only: [:show, :edit, :update] do
      collection do
        post :edit_confirm
      end
    end
  end

  # resources :admins, only: [] do
  resources :admins, path: '/admins', param: :username, only: [] do
    scope module: 'admins' do
      resources :jobs, only: [:index, :show] do
      end
    end
  end

  root 'employees/jobs#index'


end

app/controllers/admins/jobs_controller.rb
class Admins::JobsController < ApplicationController
  protect_from_forgery except: :index
  before_action :set_root_departments, only: [:index, :show]
  before_action :set_job_statuses, only: [:index]

  def index
    # public_status_id = JobStatus.find_by(name: '公開中').id
    if params[:status].present?
      status_filter = [params[:status].to_i]
    elsif params[:status] == ''
      status_filter = JobStatus.pluck(:id)
    else
      status_filter = [JobStatus.find_by(name: '公開中').id] # デフォルトは公開中の求人のみを表示
    end


    if params[:department].present? && params[:department] =~ /\A\d+\z/
      department_filter = Department.find(params[:department].to_i).subtree.pluck(:id)
      @department_name = Department.find_by(id: params[:department]).path.map(&:name).join
    else
      department_filter = Department.all.pluck(:id)
      @department_name = "すべて部門の求人"
    end

    sub_query = JobStatusMap.select('job_id, MAX(created_at) as max_created_at').group(:job_id)

    @q = Job.ransack(params[:q])
    @jobs = @q.result
          .includes(:category, job_status_maps: :job_status)
          .joins(:job_status_maps)
          .joins("INNER JOIN (#{sub_query.to_sql}) AS latest_statuses ON job_status_maps.job_id = latest_statuses.job_id AND job_status_maps.created_at = latest_statuses.max_created_at")
          .where(department_id: department_filter, job_status_maps: { job_status_id: status_filter })
          .order('job_status_maps.created_at DESC')
          .page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js # これを追加
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  private

  def set_root_departments
    @root_departments = Department.where(ancestry: nil)
  end

  def set_job_statuses
    @job_statuses = JobStatus.all
  end
end

app/controllers/employees/jobs_controller.rb
class Employees::JobsController < ApplicationController
  protect_from_forgery except: :index
  before_action :set_root_departments, only: [:index, :show]
  before_action :set_categories, only: [:index]

  def index
    public_status_id = JobStatus.find_by(name: '公開中').id

    category_filter = if params[:category].present?
      category = Category.find(params[:category].to_i)
    else
      Category.all.pluck(:id)
    end

    if params[:department].present? && params[:department] =~ /\A\d+\z/
      department_filter = Department.find(params[:department].to_i).subtree.pluck(:id)
      @department_name = Department.find_by(id: params[:department]).path.map(&:name).join
    else
      department_filter = Department.all.pluck(:id)
      @department_name = "すべて部門の求人"
    end

    sub_query = JobStatusMap.select('job_id, MAX(created_at) as max_created_at').group(:job_id)

    @q = Job.ransack(params[:q])
    @jobs = @q.result
          .includes(:category, job_status_maps: :job_status)
          .joins(:job_status_maps)
          .joins("INNER JOIN (#{sub_query.to_sql}) AS latest_statuses ON job_status_maps.job_id = latest_statuses.job_id AND job_status_maps.created_at = latest_statuses.max_created_at")
          .where(department_id: department_filter, category_id: category_filter, job_status_maps: { job_status_id: public_status_id })
          .order('job_status_maps.created_at DESC')
          .page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.js # これを追加
    end
  end

  def show
    session.delete(:job_application_data) if session[:job_application_data]
    @job = Job.find(params[:id])

    # if current_employee
    #   @already_applied = JobApplication.exists?(job: @job, applicant: current_employee.employee_profile)
    # else
    #   @already_applied = false
    # end
    if current_employee
      @already_applied = JobApplication.exists?(job: @job, applicant: current_employee.employee_profile)
      @same_department = @job.department == current_employee.employee_profile.department
    else
      @already_applied = false
      @same_department = false
    end
  end

  private

  def set_root_departments
    @root_departments = Department.where(ancestry: nil)
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/recruiters/confirmations_controller.rb
# frozen_string_literal: true

class Recruiters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/recruiters/jobs_controller.rb
class Recruiters::JobsController < ApplicationController
  helper Recruiters::JobsHelper
  protect_from_forgery except: :index
  before_action :authenticate_recruiter!
  before_action :set_instances_for_form, only: [:index, :back, :new, :confirm, :create, :edit, :edit_confirm, :back_edit, :update]
  before_action :set_job_statuses, only: [:index]

  def index
    session.delete(:job) if session[:job]
    @recruiter_sub_departments = @recruiter_department.subtree
    if params[:status].present?
      status_filter = [params[:status].to_i]
    elsif params[:status] == ''
      status_filter = JobStatus.pluck(:id)
    else
      status_filter = [JobStatus.find_by(name: '公開中').id] # デフォルトは公開中の求人のみを表示
    end

    if params[:department].present? && params[:department] =~ /\A\d+\z/
      department_filter = [params[:department].to_i]
      @department_name = Department.find_by(id: params[:department]).path.map(&:name).drop(@recruiter_department_depth + 1).join
    else
      department_filter = @recruiter_sub_departments.pluck(:id)
      @department_name = @recruiter_department_name
    end

    sub_query = JobStatusMap.select('job_id, MAX(created_at) as max_created_at').group(:job_id)

    @q = Job.ransack(params[:q])
    @jobs = @q.result
            .includes(:category, :job_applications, job_status_maps: :job_status)
            .joins(:job_status_maps)
            .joins("INNER JOIN (#{sub_query.to_sql}) AS latest_statuses ON job_status_maps.job_id = latest_statuses.job_id AND job_status_maps.created_at = latest_statuses.max_created_at")
            .where(department_id: department_filter, job_status_maps: { job_status_id: status_filter })
            .order('job_status_maps.created_at DESC')
            .page(params[:page]).per(10).all

    respond_to do |format|
      format.html
      format.js # これを追加
    end
  end

  def new
    if session[:job]
      @job = Job.new(session[:job])
      @recruiters = RecruiterProfile.where(department_id: @job.department_id)
      # @contact_persons = RecruiterProfile.where(id: session[:job]["contact_person_ids"].reject(&:blank?)).pluck(:id)
      @contact_person_ids = session.dig(:job, "contact_person_ids")&.reject(&:blank?) || []
      session.delete(:job)
    else
      @job = Job.new
    end
  end

  def confirm
    @job = Job.new(job_params)
    if @job.valid?
      @current_job_status = JobStatus.find(@job.job_status_id).name
      @contact_persons = RecruiterProfile.where(id: @job.contact_person_ids.reject(&:blank?))
      session[:job] = job_params
    else
      set_instances_for_form
      @contact_person_ids = @job.contact_person_ids.reject(&:blank?)
      render :new
    end
  end

  def create
    @job = Job.new(session[:job])
    contact_person_ids = RecruiterProfile.where(id: session[:job]["contact_person_ids"].reject(&:blank?)).pluck(:id)
    session.delete(:job)
    if @job.save
      @job.update_contact_persons(contact_person_ids)
      redirect_to recruiter_jobs_path, notice: '新規求人を作成しました'
    else
      set_instances_for_form
      @recruiters = @job.department.recruiter_profiles
      render :new
    end
  end

def edit
  @job = Job.find(params[:id])
  @recruiters = @job.department.recruiter_profiles
  @contact_person_ids = @job.contact_persons.pluck(:id)
  @job.job_status_id = @job.job_status_maps.last&.job_status_id
  if session[:job]
    @job.assign_attributes(session[:job])
    @contact_person_ids = @job.contact_person_ids
    session.delete(:job)
  end
  @job.previous_job_status_id = @job.current_status
end

  def edit_confirm
    @job = Job.find(params[:id])
    @job.assign_attributes(job_params)
    @current_job_status = JobStatus.find(@job.job_status_id).name
    @contact_persons = RecruiterProfile.where(id: @job.contact_person_ids.reject(&:blank?))
    session[:job] = job_params.merge(id: @job.id)
    render :edit if @job.invalid?
  end


  def update
    @job = Job.find(session[:job]['id'])
    @job.assign_attributes(session[:job])
    contact_person_ids = session[:job]['contact_person_ids']
    session.delete(:job)
    if @job.save
      @job.update_contact_persons(contact_person_ids)
      redirect_to recruiter_jobs_path, notice: '求人情報を更新しました'
    else
      set_instances_for_form
      render :edit
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    redirect_to recruiter_jobs_path, notice: "求人を削除しました。"
  end


  def fetch_recruiters
    @recruiters = RecruiterProfile.where(department_id: params[:department_id])
    respond_to do |format|
      format.json { render json: @recruiters.map { |r| { id: r.id, name: r.full_name } } }
    end
  end

  private

  def job_params
    params.require(:job).permit(:category_id, :title, :department_id, :work_location_id, :job_description, :application_requirement, :job_status_id, contact_person_ids: []).tap do |whitelisted|
      contact_ids = whitelisted[:contact_person_ids].reject(&:blank?)
      whitelisted[:contact_person_ids] = contact_ids
    end
  end


  def set_instances_for_form
    set_recruiter_department
    set_recruiter_department_name
    set_recruiter_sub_departments
    set_recruiter_department_depth
    set_categories
    set_work_locations
    department_id = params.dig(:job, :department_id) || @job&.department_id
    @recruiters = RecruiterProfile.where(department_id: department_id) if department_id.present?
  end

  def set_recruiter_department
    @recruiter_department = current_recruiter.recruiter_profile.department
  end

  def set_recruiter_department_name
    @recruiter_department_name = @recruiter_department.path.map(&:name).join
  end

  def set_recruiter_sub_departments
    @recruiter_sub_departments = @recruiter_department.subtree
  end

  def set_recruiter_department_depth
    @recruiter_department_depth = @recruiter_department.depth
  end

  def set_categories
    @categories = Category.all
  end

  def set_job_statuses
    @job_statuses = JobStatus.all
  end

  def set_work_locations
    @work_locations = WorkLocation.all
  end

end

app/controllers/recruiters/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Recruiters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/recruiters/passwords_controller.rb
# frozen_string_literal: true

class Recruiters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/recruiters/registrations_controller.rb
# frozen_string_literal: true

class Recruiters::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    # super(resource)
    edit_recruiter_registration_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/recruiters/sessions_controller.rb
# frozen_string_literal: true

class Recruiters::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def after_sign_in_path_for(resource)
    # super(resource)
    recruiter_jobs_path(resource)
  end

  # def after_sign_out_path_for(resource_or_scope)
  #   new_recuruiter_session_path
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/recruiters/unlocks_controller.rb
# frozen_string_literal: true

class Recruiters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
end

app/helpers/admins/jobs_helper.rb
module Admins::JobsHelper
end

app/helpers/employees/jobs_helper.rb
module Employees::JobsHelper
end

app/helpers/recruiters/applicants_helper.rb
module Recruiters::ApplicantsHelper
end

app/helpers/recruiters/jobs_helper.rb
module Recruiters::JobsHelper
  # def job_status_color(status_name)
  #   case status_name
  #   when '未公開'
  #     'bg-gray-200 text-gray-900'
  #   when '公開中'
  #     'bg-green-200 text-green-900'
  #   when '募集終了'
  #     'bg-red-200 text-red-900'
  #   else
  #     'bg-blue-200 text-blue-900' # 予期しないステータスの場合のデフォルトの色
  #   end
  # end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/recruiters/jobs/_jobs_paginate.html.erb
<%= render partial: 'list', locals: { jobs: @jobs } %>
<%= paginate @jobs, remote: true %>

app/views/recruiters/jobs/_list.html.erb
<table id="job-list" class="min-w-full leading-normal">
  <thead class="sticky-thead">
    <tr>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        求人番号
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        求人タイトル
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        職種
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        部門
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        ステータス
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        公開日
      </th>
      <th
        class="px-4 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider sticky-thead">
        応募者数
      </th>
    </tr>
  </thead>
  <tbody>
    <% jobs.each do |job| %>
    <tr>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap">
          <%= job.id %>
        </p>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap">
            <%= link_to job.title, edit_recruiter_job_path(current_recruiter, job), class: "custom-link" %>
        </p>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap">
            <%= job.category.name %>
        </p>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap">
            <%= job.department.path.map(&:name).drop(@recruiter_department_depth + 1).join %>
        </p>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <span
          class="relative inline-block px-3 py-1 font-semibold leading-tight">
          <span aria-hidden
              class="absolute inset-0 opacity-50 rounded-full"></span>
          <span class="relative"><%= job.current_status.name %></span>
        </span>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap">
            <%= job.job_status_maps.order(created_at: :desc).first.job_status.created_at.strftime("%Y-%m-%d") %>
        </p>
      </td>
      <td class="px-4 py-2 border-b border-gray-200 bg-white text-sm">
        <p class="whitespace-no-wrap">
          <%= link_to job.job_applications.count, job_applicants_path(job), class: "custom-link"%>
        </p>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/recruiters/jobs/edit.html.erb
<body data-fetch-recruiters-url="<%= fetch_recruiters_recruiter_jobs_path %>" data-contact-person-ids="<%= @job.contact_persons.pluck(:id).join(",") || 'null' %>" class="bg-gray-100 font-family-karla flex overflow-y-auto">
  <%= render partial: "recruiters/shared/aside" %>
  <div class="relative w-full flex flex-col content-offset">
    <%= render partial: "recruiters/shared/header" %>
    <div class="w-full border-t flex flex-col">
      <main class="w-full p-6">
        <h1 class="w-full text-3xl text-black sticky top-12 z-10 bg-gray-100 mb-6 pb-8">求人編集画面</h1>
        <div class="flex justify-center items-center w-full mt-6 pl-0 lg:pl-2">
          <div class="leading-loose w-2/3">
          <div class="mt-4 p-2 w-full text-right">
            <%= button_to "この求人を削除する", recruiter_job_path(current_recruiter, @job), method: :delete, class: "btn inline-block px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded text-lg", onclick: "return confirm('求人を削除します。よろしいですか？');" %>
          </div>
          <%= form_with model: @job, url: edit_confirm_recruiter_job_path(current_recruiter, @job), local: true do |f| %>
            <%= render partial: 'form', locals: { f: f, job_statuses: JobStatus.all } %>
          <% end %>
          </div>
        </div>
      </main>
    </div>
  </div>
  <%= javascript_include_tag "recruiters/new", defer: true %>
</body>

app/views/recruiters/jobs/edit_confirm.html.erb
<body class="bg-gray-100 font-family-karla flex overflow-y-auto">
  <%= render partial: "recruiters/shared/aside" %>
  <div class="relative w-full flex flex-col content-offset">
    <%= render partial: "recruiters/shared/header" %>
    <div class="w-full border-t flex flex-col">
      <main class="w-full p-6">
        <h1 class="w-full text-3xl text-black sticky top-12 z-10 bg-gray-100 mb-6 pb-8">求人編集確認画面</h1>
        <div class="flex justify-center items-center w-full mt-6 pl-0 lg:pl-2">
          <div class="leading-loose w-2/3">
            <%= render partial: "content" %>
            <div class="flex justify-between mt-8 p-2 w-full">
              <%= link_to "編集画面に戻る", edit_recruiter_job_path, class: "btn flex bg-gray-300 hover:bg-gray-400 text-gray-800 py-2 px-4 rounded" %>
              <%= form_with model: @job, url: recruiter_job_path(@job), method: :patch, local: true do |f| %>
                <%= f.submit "更新する", class: "btn flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" %>
              <% end %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
  <%= javascript_include_tag "recruiters/new", defer: true %>
</body>

app/views/recruiters/jobs/index.html.erb
<body data-recruiter-username="<%= current_recruiter.username %>" class="bg-gray-100 font-family-karla flex">
  <%= render partial: "recruiters/shared/aside" %>
  <div class="relative w-full flex flex-col content-offset h-screen overflow-y-auto">
    <%= render partial: "recruiters/shared/header" %>
    <div class="w-full border-t flex flex-col bg-gray-100">
      <main class="w-full flex-grow p-6">
        <div class="fixed-content bg-gray-100 pb-8">
          <h1 class="text-3xl text-black pb-6">求人一覧</h1>
          <div class="flex justify-between items-center mb-4">
            <p class="pb-3"><%= @department_name %></p>
            <%= link_to "新規求人作成", new_recruiter_job_path, class: "btn flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" %>
          </div>
          <div class="flex">
            <%= form_with(url: jobs_path, method: :get, local: true, remote: true, id: 'job-status-filter-form', class: 'w-1/6 mr-2') do |f| %>
              <%= f.hidden_field :department, value: params[:department] %>
                <label class="block text-sm text-gray-600">ステータス</label>
                <%= f.select :status, options_for_select(@job_statuses.map { |status| [status.name, status.id] }.unshift(['すべて', '']), selected: params[:status] || 2), {}, { class: "px-2 py-2 w-full text-gray-700 rounded" } %>
            <% end %>
            <%= search_form_for @q, url: jobs_path, remote: true, html: { id: 'search-form', class: 'ml-2 w-1/3' } do |f| %>
                <%= f.label :global_search_cont, "キーワード", class: "block text-sm text-gray-600" %>
                <%= f.search_field :global_search_cont, class: "px-2 py-2 w-full text-gray-700 rounded" %>
                <%= f.submit "Search", style: "display: none;" %>
            <% end %>
          </div>
        </div>
        <% if @jobs.any? %>
          <div id="jobs" class="w-full bg-gray-100 flex-grow">
            <%= render partial: 'jobs_paginate', locals: { jobs: @jobs } %>
          </div>
        <% else %>
          <p class="mt-4 text-center text-red-600">現在この条件に該当する求人はありません</p>
        <% end %>
      </main>
    </div>
  </div>
  <%= javascript_importmap_tags "recruiters/index" %>
</body>

app/views/recruiters/jobs/index.js.erb
let jobsPaginate = document.querySelector('#jobs');
<% if @jobs.present? %>
  jobsPaginate.innerHTML = '<%= j render(partial: 'jobs_paginate', locals: { jobs: @jobs }) %>';
  history.replaceState( "", "" ,"?page=<%= @page %>");
<% else %>
  jobsPaginate.innerHTML = '<p class="mt-4 text-center text-red-600">現在この条件に該当する求人はありません</p>';
<% end %>

document.querySelector('p.pb-3').textContent = '<%= @department_name %>';

app/views/recruiters/jobs/new.html.erb
<body data-contact-person-id="<%= @job.contact_person_ids ? @job.contact_person_ids.join(",") : 'null' %>" class="bg-gray-100 font-family-karla flex overflow-y-auto">
  <%= render partial: "recruiters/shared/aside" %>
  <div class="relative w-full flex flex-col content-offset">
    <%= render partial: "recruiters/shared/header" %>
    <div class="w-full border-t flex flex-col">
      <main class="w-full p-6">
        <h1 class="w-full text-3xl text-black sticky top-12 z-10 bg-gray-100 mb-6 pb-8">新規求人作成画面</h1>
        <div class="flex justify-center items-center w-full mt-6 pl-0 lg:pl-2">
          <div class="leading-loose w-2/3">
            <%= form_with model: @job, url: confirm_recruiter_jobs_path, html: { data: { url: fetch_recruiters_recruiter_jobs_path(username: current_recruiter.username) } } do |f| %>
              <%= render partial: 'form', locals: { f: f, job_statuses: JobStatus.where(id: [1, 2]) } %>
            <% end %>
          </div>
        </div>
      </main>
    </div>
  </div>
  <%= javascript_include_tag "recruiters/new", defer: true %>
</body>