config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :recruiters, controllers: {
    sessions:      'recruiters/sessions',
    passwords:     'recruiters/passwords',
    registrations: 'recruiters/registrations'
  }

  devise_for :employees, controllers: {
    sessions:      'employees/sessions',
    passwords:     'employees/passwords',
    registrations: 'employees/registrations'
  }

  resources :recruiters, path: '/recruiters', param: :username, only: [] do
    scope module: 'recruiters' do
      resources :jobs, only: [:index, :create, :new, :edit, :update, :destroy] do
        # resources :applicants, only: [:index, :show, :update]  # 追加
        collection do
          post :confirm
          get :fetch_recruiters, defaults: { format: 'json' }
        end
        member do
          patch :edit_confirm
        end
      end
    end
  end


  resources :jobs, module: 'employees', only: [:index, :show] do
    resources :job_applications, only: [:new, :create] do
      collection do
        post :confirm
      end
    end
  end

  resources :jobs do
    resources :applicants, only: [:index, :show, :edit, :update]
  end

  resources :employees, param: :username, only: [] do
    resources :job_applications, module: 'employees', only: [:index, :show]
    resource :profile, module: 'employees', only: [:show, :edit, :update] do
      collection do
        post :edit_confirm
      end
    end
  end

  # resources :admins, only: [] do
  resources :admins, path: '/admins', param: :username, only: [] do
    scope module: 'admins' do
      resources :jobs, only: [:index, :show] do
      end
    end
  end

  root 'employees/jobs#index'


end

app/views/admins/shared/_aside.html.erb
<aside class="relative bg-sidebar w-1/6 hidden sm:block shadow-xl overflow-y-auto h-screen position-fixed flex flex-col items-center">
  <div class="p-6 w-full flex justify-center">
    <%= link_to admin_jobs_path(admin_username: current_admin.username), class: "flex title-font font-medium items-center text-gray-900" do %>
      <%= image_tag 'logo.png', class: 'w-28 h-28 rounded-full' %>
    <% end %>
  </div>
  <nav class="text-white text-base font-semibold pt-3 w-full flex flex-col items-center">
    <div class="">
      <%= link_to "#すべての求人", admin_jobs_path(admin_username: current_admin.username), data: { department_id: '' }, class: 'block px-4 py-2 mt-2 department-link' %>
      <% @root_departments.each do |department| %>
        <%= link_to department.name, admin_jobs_path(admin_username: current_admin.username, department: department.id), data: { department_id: department.id }, class: 'block px-4 py-2 mt-2 department-link' %>
      <% end %>
    </div>
  </nav>
</aside>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_header.html.erb
<!-- Desktop Header -->
<header class="w-full items-center bg-white py-3 px-6 hidden sm:flex header-fixed">
  <div class="w-1/2"></div>
  <div x-data="{ isOpen: false }" class="relative w-1/2 flex justify-end">
      <button @click="isOpen = !isOpen" class="realtive z-10 focus:outline-none">
          <%= current_admin.username %>
      </button>
      <button x-show="isOpen" @click="isOpen = false" class="h-full w-full fixed inset-0 cursor-default"></button>
      <div x-show="isOpen" x-cloak class="absolute w-32 bg-white rounded-lg shadow-lg py-2 mt-16">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :get, class: "block px-4 py-2 account-link hover:text-white" %>
      </div>
  </div>
</header>

<!-- Mobile Header & Nav -->
<header x-data="{ isOpen: false }" class="w-full bg-sidebar py-5 px-6 sm:hidden">
  <div class="flex items-center justify-between">
      <a href="index.html" class="text-white text-3xl font-semibold uppercase hover:text-gray-300">Admin</a>
      <button @click="isOpen = !isOpen" class="text-white text-3xl focus:outline-none">
          <i x-show="!isOpen" class="fas fa-bars"></i>
          <i x-show="isOpen" class="fas fa-times"></i>
      </button>
  </div>

  <!-- Dropdown Nav -->
  <nav :class="isOpen ? 'flex': 'hidden'" class="flex flex-col pt-4">
      <a href="index.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-tachometer-alt mr-3"></i>
          Dashboard
      </a>
      <a href="blank.html" class="flex items-center active-nav-link text-white py-2 pl-4 nav-item">
          <i class="fas fa-sticky-note mr-3"></i>
          Blank Page
      </a>
      <a href="tables.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-table mr-3"></i>
          Tables
      </a>
      <a href="forms.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-align-left mr-3"></i>
          Forms
      </a>
      <a href="tabs.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-tablet-alt mr-3"></i>
          Tabbed Content
      </a>
      <a href="calendar.html" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-calendar mr-3"></i>
          Calendar
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-cogs mr-3"></i>
          Support
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-user mr-3"></i>
          My Account
      </a>
      <a href="#" class="flex items-center text-white opacity-75 hover:opacity-100 py-2 pl-4 nav-item">
          <i class="fas fa-sign-out-alt mr-3"></i>
          Sign Out
      </a>
      <button class="w-full bg-white cta-btn font-semibold py-2 mt-3 rounded-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
          <i class="fas fa-arrow-circle-up mr-3"></i> Upgrade to Pro!
      </button>
  </nav>
  <!-- <button class="w-full bg-white cta-btn font-semibold py-2 mt-5 rounded-br-lg rounded-bl-lg rounded-tr-lg shadow-lg hover:shadow-xl hover:bg-gray-300 flex items-center justify-center">
      <i class="fas fa-plus mr-3"></i> New Report
  </button> -->
</header>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>